# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b1c7b2273c0c19c3affe0c0bb917a2b2aaa5290879a84edcd10cf5676bb190e7d6c5ca7ad818c88c5eda8a98a6db9740973010b5c8adf9e2b0aa9677875d63

test:
  secret_key_base: 251a64bd7bd6d875b1eabc0e484003fb88c4196aeda3987892f3f1002a677d45f4f4aee58d0f1b0cde95f9c1ccba1f1307cd33e671366138ea73faf9146a98e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
